from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    CommentDetailView,
    CommentCreateView,
    CommentUpdateView,
    CommentDeleteView,
    CommentReportView,
    ReplyDetailView,
    ReplyCreateView,
    ReplyUpdateView,
    ReplyDeleteView,
    ReplyReportView,
    ContactView,
    SearchPostListView)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/comment/new/', CommentCreateView.as_view(), name='comment-create'),
    path('post/<int:pk>/comment/<int:id>/', CommentDetailView.as_view(), name='comment-detail'),
    path('post/<int:pk>/comment/<int:id>/update/', CommentUpdateView.as_view(), name='comment-update'),
    path('post/<int:pk>/comment/<int:id>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
    path('post/<int:pk>/comment/<int:id>/report/', CommentReportView.as_view(), name='comment-report'),
    path('post/<int:pk>/comment/<int:id>/reply/new/', ReplyCreateView.as_view(), name='reply-create'),
    path('post/<int:pk>/comment/<int:id>/reply/<int:key>/', ReplyDetailView.as_view(), name='reply-detail'),
    path('post/<int:pk>/comment/<int:id>/reply/<int:key>/update/', ReplyUpdateView.as_view(), name='reply-update'),
    path('post/<int:pk>/comment/<int:id>/reply/<int:key>/delete/', ReplyDeleteView.as_view(), name='reply-delete'),
    path('post/<int:pk>/comment/<int:id>/reply/<int:key>/report/', ReplyReportView.as_view(), name='reply-report'),
    path('about/', views.about, name='blog-about'),
    path('contact/', ContactView.as_view(), name='blog-contact'),
    path('calendar/', views.calendar, name='blog-calendar'),
    path('announcements/', views.announcements, name='blog-announcements'),
    path('upcoming-events/', views.upcoming_events, name='blog-upcoming-events'),
    path('mailing-list/', views.mailing_list_detail, name='mailing-list-detail'),
    path('mailing-list/subscribe/', views.mailing_list_subscribe, name='mailing-list-subscribe'),
    path('mailing-list/unsubscribe/', views.mailing_list_unsubscribe, name='mailing-list-unsubscribe'),
    path('mailing-list/subscribe/done/', views.mailing_list_subscribe_done, name='mailing-list-subscribe-done'),
    path('mailing-list/unsubscribe/done/', views.mailing_list_unsubscribe_done, name='mailing-list-unsubscribe-done'),
    path('search/', views.search, name='search-posts'),
    path('search/results/<str:query>/', SearchPostListView.as_view(), name='search-results')
]